#### Feature Scaling

##### Importing Libraries and Loading Data

In [11]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import RobustScaler
import joblib

project_root = Path.cwd().parent
processed_dir = project_root /'data'/'processed'
models_dir = project_root /'models'

features = pd.read_parquet(processed_dir/'station_features.parquet')

##### Robust Scaling

In [12]:
# Robust Scaling works best as it handles outliers better

scaler = RobustScaler()
scaled_values = scaler.fit_transform(features)

In [13]:
features_scaled = pd.DataFrame(
    scaled_values,
    index=features.index,
    columns=features.columns
)

In [14]:
features_scaled.head()

,log_total_weekday,early_share,eve_share,late_share,peakness,am_asym,pm_asym,weekend_shift,weekend_ratio,lines_served,interchange_ratio
nlc,,,,,,,,,,,
750,-0.862447,0.243759,0.337337,0.641688,-0.663250,-0.305477,0.400954,-0.427657,0.003162,0.0,0.000000
1404,-0.725928,0.169494,0.120946,0.192606,-0.232571,-0.342659,0.082545,0.114390,-0.297051,0.0,0.000000
3000,-0.104848,0.184460,-0.327957,-0.298239,0.265232,0.159342,-0.020733,0.350321,0.337970,0.0,0.000000
500,0.186290,-0.048123,-0.219895,-0.031235,0.048782,-0.082235,0.179439,-0.141977,0.157152,1.0,13.638486
502,0.578366,-0.504523,0.835659,0.723786,0.762086,-1.453377,1.220046,-0.005377,-1.331137,1.0,0.560999

In [15]:
features_scaled.shape

(432, 11)

In [16]:
features_scaled.describe().T

,count,mean,std,min,25%,50%,75%,max
log_total_weekday,432.0,0.046553,0.808813,-2.563432,-0.505298,-7.426785e-16,0.494702,2.601037
early_share,432.0,0.170983,0.666754,-0.725616,-0.370242,4.423545e-17,0.629758,2.546118
eve_share,432.0,0.184748,0.768285,-0.923628,-0.412337,1.105886e-16,0.587663,3.518500
late_share,432.0,0.360327,1.042818,-0.715648,-0.324157,-5.767956e-17,0.675843,6.742930
peakness,432.0,0.104710,0.750113,-1.398145,-0.444506,0.000000e+00,0.555494,3.672683
am_asym,432.0,-0.210710,0.709327,-2.034879,-0.653228,0.000000e+00,0.346772,0.837290
pm_asym,432.0,0.096940,0.701445,-1.333908,-0.421839,3.295975e-17,0.578161,1.908592
weekend_shift,432.0,0.096748,0.841236,-2.053157,-0.397948,-2.758210e-16,0.602052,2.826884
weekend_ratio,432.0,0.058134,0.984335,-2.635553,-0.486393,0.000000e+00,0.513607,7.108784
lines_served,432.0,0.317130,0.700602,0.000000,0.000000,0.000000e+00,0.000000,5.000000
interchange_ratio,432.0,1.853408,4.064561,0.000000,0.000000,0.000000e+00,1.000000,19.387869

In [17]:
# Saving

features_scaled.to_parquet(processed_dir/'station_features_scaled.parquet')
joblib.dump(scaler, models_dir/'scaler.joblib')

['C:\\Users\\Abdul Qudus\\Documents\\Data Portfolio\\london-transit-archetypes\\models\\scaler.joblib']